config/routes.rb
Tatooine::Application.routes.draw do

  get "feedbacks/create"

  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  get '/admin/locale/:locale' => 'admin/dashboard#set_locale'

  get 'reset' => 'home#reset'
  root to: 'home#index', as: :root
  
  resources :courses do
    resources :feedbacks
    resources :course_sessions do
      resources :sections
      member do
        post 'resort'
      end
    end
    
    resources :badges
    
    member do
      post 'enroll'
      get 'faq'
      get 'ranking'
      get 'stats'
    end
    
    collection do
      get 'search'
    end
    
  end
  
  resources :sections do
    resources :exercises
    resources :attachments
  end
  
  resources :exercises do
    member do
      put 'customize'
      put 'solve'
    end
  end
  
  resources :teachers
  resources :students
  
  resources :users do
    member do
      get 'stats/:course_id' => 'users#course_stats', as: 'stats'
    end
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @my_students = current_user.students
  end

  def show
    @student = User.find params[:id]
    @courses = Course.availables.taken_by(@student)
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/index.html.slim
h2 Tus alumnos
- unless @my_students.empty?
	ul.courses
	- for student in @my_students
	  li= tile_to student.name, student_path(student), background: [student, :avatar]
- else
    p No presenta alumnos actualmente

app/views/students/show.html.slim
h2 Cursos dictados por #{link_to @student.complete_name, @student}
ul.courses
  - for course in @courses
    li= link_to course.name, course_url(course), class: 'course_tile'