config/routes.rb
Tatooine::Application.routes.draw do

  get "feedbacks/create"

  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  get '/admin/locale/:locale' => 'admin/dashboard#set_locale'

  get 'reset' => 'home#reset'
  root to: 'home#index', as: :root
  
  resources :courses do
    resources :feedbacks
    resources :course_sessions do
      resources :sections
      member do
        post 'resort'
      end
    end
    
    resources :badges
    
    member do
      post 'enroll'
      get 'faq'
      get 'ranking'
      get 'stats'
    end
    
    collection do
      get 'search'
    end
    
  end
  
  resources :sections do
    resources :exercises
    resources :attachments
  end
  
  resources :exercises do
    member do
      put 'customize'
      put 'solve'
    end
  end
  
  resources :teachers
  resources :students
  
  resources :users do
    member do
      get 'stats/:course_id' => 'users#course_stats', as: 'stats'
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @courses = Course.availables
      @teachers = User.teachers
    else
      load_featured_courses
      render 'login'
    end
  end

  def reset
    reset_session
    redirect_to root_path
  end
  
  private
  
  def load_featured_courses
    # Cambiar esto por algo más inteligente. Sólo estoy haciendo la implementación más simple.
    @featured_courses = Course.availables
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
h2= "Bienvenido, #{current_user.name}"

p Bienvenido a tatooine, te recomendamos revisar nuestra lista de cursos y profesores populares para empezar.

h2 Cursos recomendados
ul.courses
  - for course in @courses
    li= course_tile_to course

h2 Profesores recomendados
ul.courses
  - for teacher in @teachers
    li= tile_to teacher.name, teacher_path(teacher)

app/views/home/login.html.slim
- @body_classes = "login"

.super-home
  header.inside
    h1 Tatooine
    blockquote "May The Force Be With You"
  .band-of-power
  section#more.inside
    h2
      span ¿Qué es Tatooine?
    .explanation.what-is-tatooine
      p Tatooine es una plataforma de aprendizaje virtual. Puedes tomar los cursos que desees y dictar tus propios cursos.
      p Cada curso está divido en clases, que puedes llevar en el tiempo que quieras. Estas clases se separan en secciones, que se enfocan en un punto específico de la lección.
      p También puedes insertar presentaciones, videos y archivos en tus clases.
    h2
      span Cursos recomendados
    .explanation.some-courses
      ul.courses
        - for course in @featured_courses
          li= tile_to course.name, course_path(course)
    h2
      span Aprende
    .explanation.learn
      p En Tatooine puedes aprender cursos dictados por cualquier persona. Puedes incluso aprender cosas poco comunes de forma sencilla.
    h2
      span Enseña
    .explanation.teach
      p Aparte de aprender, tienes la posibilidad de enseñar en todo momento. En Tatooine, todos podemos ser maestros de todos. Podrías terminar enseñándole algo a tu profesor de escuela.
    h2
      span Comienza tu camino
    .explanation.begin-your-path
      p Iniciar en Tatooine es sencillo. Sólo regístrate o, si se te hace muy engorroso llenar un formulario, conéctate por medio de Facebook o Twitter. Que la fuerza te acompañe.