config/routes.rb
Tatooine::Application.routes.draw do

  get "feedbacks/create"

  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  get '/admin/locale/:locale' => 'admin/dashboard#set_locale'

  get 'reset' => 'home#reset'
  root to: 'home#index', as: :root
  
  resources :courses do
    resources :feedbacks
    resources :course_sessions do
      resources :sections
      member do
        post 'resort'
      end
    end
    
    resources :badges
    
    member do
      post 'enroll'
      get 'faq'
      get 'ranking'
      get 'stats'
    end
    
    collection do
      get 'search'
    end
    
  end
  
  resources :sections do
    resources :exercises
    resources :attachments
  end
  
  resources :exercises do
    member do
      put 'customize'
      put 'solve'
    end
  end
  
  resources :teachers
  resources :students
  
  resources :users do
    member do
      get 'stats/:course_id' => 'users#course_stats', as: 'stats'
    end
  end
  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @my_teachers = current_user.teachers
    @teachers = User.teachers
  end

  def show
    @teacher = User.find params[:id]
    @courses = Course.availables.created_by(@teacher)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/index.html.slim
h2 Tus profesores
- unless @my_teachers.empty?
	ul.courses
	  - for teacher in @my_teachers
	    li= tile_to teacher.name, teacher_path(teacher), background: [teacher, :avatar]
- else
	p No te has inscrito a algún curso todavía.

h2 Todos los profesores
ul.courses
  - for teacher in @teachers
    li= tile_to teacher.name, teacher_path(teacher), background: [teacher, :avatar]

app/views/teachers/show.html.slim
h2 Cursos dictados por #{link_to @teacher.complete_name, @teacher}
ul.courses
  - for course in @courses
    li= link_to course.name, course_url(course), class: 'course_tile'