config/routes.rb
Tatooine::Application.routes.draw do

  get "feedbacks/create"

  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  get '/admin/locale/:locale' => 'admin/dashboard#set_locale'

  get 'reset' => 'home#reset'
  root to: 'home#index', as: :root
  
  resources :courses do
    resources :feedbacks
    resources :course_sessions do
      resources :sections
      member do
        post 'resort'
      end
    end
    
    resources :badges
    
    member do
      post 'enroll'
      get 'faq'
      get 'ranking'
      get 'stats'
    end
    
    collection do
      get 'search'
    end
    
  end
  
  resources :sections do
    resources :exercises
    resources :attachments
  end
  
  resources :exercises do
    member do
      put 'customize'
      put 'solve'
    end
  end
  
  resources :teachers
  resources :students
  
  resources :users do
    member do
      get 'stats/:course_id' => 'users#course_stats', as: 'stats'
    end
  end
  
end

app/controllers/courses_controller.rb
# encoding: utf-8
class CoursesController < ApplicationController
  include CoursesProtector
  
  before_filter :authenticate_user!, except: [:show, :faq]
  before_filter :load_course, except: [:index, :new, :create]
  before_filter :load_courses, only: [:index]
  before_filter :reject_unpublished_courses, only: [:show, :faq, :stats, :ranking]
  
  before_filter :protect_courses, only: [:edit, :update, :destroy, :stats]

  def index
    @levels = Level.select([:name]).map(&:name)
    
    if @search
      original_source = @courses
      
      @available_courses = original_source.availables.to_a
      @courses = original_source.to_a # fetch the query
      
      @your_level_courses = Course.with_level(current_user.average_level, {array: @available_courses})
      @courses_you_created = Course.created_by(current_user, {array: @courses})
      @courses_you_take = Course.taken_by(current_user, {array: @available_courses})
      
      @courses = original_source.availables
    else
      @your_level_courses = @courses.availables.with_level(current_user.average_level)
      @courses_you_created = @courses.created_by(current_user)
      @courses_you_take = @courses.availables.taken_by(current_user)
      
      @courses = @courses.availables
    end
  end
  
  def show
    @classes = @course.course_sessions
    
    respond_with(@course) do |format|
      format.html do
        render layout: 'show_course'
      end
    end
  end
  
  def edit
    if current_user.creations.include? @course
      respond_with(@course) do |format|
        format.html do
          render layout: 'edit_course'
        end
      end
    else
      redirect_to course_path(@course)
    end
  end
  
  def new
    @course = Course.new
    respond_with(@course)
  end
  
  def destroy
    @course = Course.find params[:id]
    @course.destroy
    redirect_to courses_path
  end
  
  def create
    @course = Course.new(params[:course])
    @course.creator = current_user
    @course.level_id = params[:course][:level_id]
    @course.save
    respond_with(@course) do |format|
      format.html do
        if @course.errors.empty?
          flash[:notice] = "¡Curso creado exitosamente!"
          redirect_to(edit_course_url(@course))
        else
          render :new
        end
      end
    end
  end
  
  def update
    @course.update_attributes(params[:course])
    respond_with(@course) do |format|
      format.html do
        if @course.errors.empty?
          flash[:notice] = "¡Curso actualizado exitosamente!"
          redirect_to(edit_course_url(@course))
        else
          flash[:alert] = format_errors(@course)
          redirect_to(edit_course_url(@course))
        end
      end
    end
  end
  
  def enroll
    enrollment = @course.add_student(current_user)
    if enrollment.errors.any?
      flash[:alert] = format_errors(enrollment)
    else
      flash[:notice] = "Has sido registrado en este curso"
    end
    redirect_to(@course)
  end
  
  def faq
    render layout: 'show_course'
  end
  
  def stats
    @ranking = @course.ranking
    @sessions = @course.course_sessions
    render layout: 'show_course'
  end
  
  def ranking
    @ranking = @course.ranking
    render layout: 'show_course'
  end
  
  private
  
  def load_courses
    @q = Course.search(params[:q])
    @search = !!params[:q]
    
    @courses = if params[:q]
      @q.result(distinct: true).joins("left join enrollments on enrollments.course_id = courses.id").joins(:level).select("courses.*, enrollments.user_id as enrollment_user_id, levels.name as level_name")
    else
      Course.where("1 = 1")
    end
  end
  
  def load_course
    @course = @course || Course.find(params[:id])
    @enrolled = if current_user
      current_user.courses.include?(@course)
    else
      false
    end
  end
  
  def reject_unpublished_courses
    load_course
    unless @course.available?
      redirect_to '/404.html'
    end
  end
  
end

app/helpers/courses_helper.rb
require 'htmlentities'

module CoursesHelper
  
  def markdown(text)
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(:hard_wrap => true),
      :no_intraemphasis => true,
      :autolink => true,
      :fenced_code_blocks => true,
      :lax_html_blocks => true)
    
    sanitize(markdown.render(text)).html_safe
  end
  
  def sanitize(html)
    dont_sanitize_inside_pre_or_code = lambda { |env|
      node = env[:node]
      if node.ancestors('pre,code').size > 0
        node.replace HTMLEntities.new.encode(node.to_s)
        { node_whitelist: [node] }
      end
    }
    
    options = {
      elements: %w{a abbr b blockquote br cite code dd dfn dl dt em i kbd li mark ol p pre q s samp small strike strong sub sup time u ul var img video audio object iframe h1 h2 h3 div},
      add_attributes: { 'a' => { 'target' => '_blank' } },
      attributes: {
        'iframe'  => %w{allowfullscreen frameborder height src width},
        'a' => %w{href},
        'img' => %w{src alt} },
      transformers: dont_sanitize_inside_pre_or_code
    }
    
    Sanitize.clean(html, options)
  end
end

app/views/courses/_form.html.slim
= semantic_form_for(@course) do |f|
  ul
    = f.input :name, label: "Nombre"
    = f.input :description, label: "Descripción"
    = f.input :available_at, as: :date_picker, label: "Disponible en:"
    = f.input :level, label: "Nivel", :include_blank => false
    .help-trigger
      = link_to_javascript "¿Cómo colocar preguntas?"
      p.help-text
        | Para colocar una pregunta, escribir:<br><br>
        |
        |   ## ¿Soy una pregunta?<br>
        |   Sí, lo eres :)<br><br>
        |
        | Eso es todo.
    = f.input :faq, as: :markdown, label: "Preguntas Frecuentes"
    = f.input :background_image, as: :file, label: "Imagen", input_html: { data: { preview: '.course-background' } }
    li.course-background-container
      - if @course.background_image.present?
        img.course-background src="#{@course.background_image.url(:thumb)}"
      - else
        img.course-background
    -# = f.input :can_be_published, label: "¿Publicar?"
    = f.submit "Guardar Curso"

app/views/courses/_search.html.slim
= search_form_for @q, :builder => Formtastic::FormBuilder, html: { id: 'search_course', class: 'formtastic' } do |f|
  ul
    = f.input :name_cont, label: "Nombre"
    = f.input :level_name_cont, label: "Nivel", include_blank: false, as: :select, collection: @levels
    = f.input :creator_first_name_or_creator_last_name_or_creator_email_cont, label: "Profesor"
    = f.submit "Buscar"

app/views/courses/edit.html.slim
- @current_tab = 'details'

app/views/courses/faq.html.slim
- @class_tab = 'faq'
- @show_primary_data = true

- content_for :more_for_courses do
  section#faq
    h2 Preguntas Frecuentes
    - if @course.faq.present?
      .faq-content== markdown @course.faq
    - else
      p No hay preguntas frecuentes todavía.

app/views/courses/index.html.slim
- @include_search = true

.courses-zone

  h2 Cursos que tomas
  
  - if @courses_you_take.empty?
    p No llevas ningún curso todavía.
  
  ul.courses
    - for course in @courses_you_take
      li= course_tile_to(course)

  h2 Cursos que dictas
  
  - if @courses_you_created.empty?
    p No dictas ningún curso todavía.
  
  ul.courses
    - for course in @courses_you_created  
      li
        = course_tile_to(course)
        = link_to "editar", edit_course_url(course), class: 'actions tile_button'
        = button_to "eliminar", course, method: 'delete', class: 'delete actions', confirm: "¿Deseas eliminar este curso?"

  = link_to 'Crear un curso', new_course_path, class: 'button'

  h2 Otros cursos de tu nivel
  
  - if @your_level_courses.empty?
    p No hay ningún curso todavía.
  
  ul.courses
    - for course in @your_level_courses
      li= course_tile_to(course)

  h2 Todos los cursos
  
  - if @courses.empty?
    p No hay ningún curso todavía.
  
  ul.courses
    - for course in @courses
      li= course_tile_to(course)

app/views/courses/new.html.slim
h2 Nuevo Curso
= render 'form'

app/views/courses/ranking.html.slim
- @class_tab = 'stats'
- @show_primary_data = true

- content_for :more_for_courses do
  h2 Ranking
  = render 'shared/ranking', ranking: @ranking, extended: false

app/views/courses/search.html.slim
h2 Cursos encontrados
h3 Criterios : 
	
ul.courses
  - for course in @results
    li= link_to course.name, course_url(course), class: 'course_tile'

app/views/courses/show.html.slim
- @class_tab = 'classes'
- @show_primary_data = true

- content_for :more_for_courses do
  section#classes
    = render 'course_sessions/index'

app/views/courses/stats.html.slim
- @class_tab = 'stats'
- @show_primary_data = true

- content_for :more_for_courses do
  .course_stats
    h2 Estadísticas por Alumno
    .rank
      = render layout: 'shared/ranking', locals: { ranking: @ranking, extended: true } do |user|
        ul.sessions
          - for session in @sessions
            li.session-rank
              h2= session.title
              - @total_progress = 0
              - @total_parts = 0
              = render 'users/session_stats', course: @course, user: user, session: session
        .total-stats
          p <span class='sect-text'>Avance Total:</span> <span class='sect-progress'>#{(@total_progress / @total_parts).round}%</span>